DROP DATABASE IF EXISTS BLOOD_EDGE;
CREATE DATABASE IF NOT EXISTS BLOOD_EDGE;
USE BLOOD_EDGE;

CREATE TABLE Section (
    Section_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    Section_title VARCHAR(20) NOT NULL,
    Section_icons_gray VARCHAR(50) NOT NULL,
    Section_icons_black VARCHAR(50) NOT NULL,
    Section_arrow VARCHAR(50) NOT NULL
);

CREATE TABLE Arsenal(
    Arsenal_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    Arsenal_title VARCHAR(30) NOT NULL,
    Arsenal_icons_gray VARCHAR(50) NOT NULL,
    Arsenal_icons_black VARCHAR(50) NOT NULL,
    Arsenal_link VARCHAR(50) NOT NULL,
    Arsenal_section_id_fk INT UNSIGNED NOT NULL,
    CONSTRAINT fk_arsenal_section
        FOREIGN KEY (Arsenal_section_id_fk) REFERENCES Section(Section_id)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TypeObjet (
    TypeObjet_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    TypeObjet_name VARCHAR(30) NOT NULL
);

CREATE TABLE Objet (
    Objet_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    Objet_arsenal_id_fk INT UNSIGNED NOT NULL,
    Objet_type_id_fk INT UNSIGNED NOT NULL,
    CONSTRAINT fk_objet_arsenal
        FOREIGN KEY (Objet_arsenal_id_fk) REFERENCES Arsenal(Arsenal_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_objet_type
        FOREIGN KEY (Objet_type_id_fk) REFERENCES TypeObjet(TypeObjet_id)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TraductionObjet (
    TraductionObjet_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    TraductionObjet_id_objet_fk INT UNSIGNED NOT NULL,
    TraductionObjet_Langages VARCHAR(5) NOT NULL,
    TraductionObjet_fields VARCHAR(30) NOT NULL,
    TraductionObjet_value TEXT NOT NULL,
    CONSTRAINT fk_trad_objet FOREIGN KEY (TraductionObjet_id_objet_fk) REFERENCES Objet(Objet_id)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE AttributObjet (
    AttributObjet INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    AttributObjet_id_objet_fk INT UNSIGNED NOT NULL,
    AttributObjet_name VARCHAR(30) NOT NULL,
    AttributObjet_value VARCHAR(50) NOT NULL,
    CONSTRAINT fk_img_objet FOREIGN KEY (AttributObjet_id_objet_fk) REFERENCES Objet(Objet_id)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Users (
    Users_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    Users_pseudo VARCHAR(50) NOT NULL UNIQUE,
    Users_email VARCHAR(100) NOT NULL UNIQUE,
    Users_hashed_password VARCHAR(255) NOT NULL,
    Users_is_accept_cgu BOOLEAN DEFAULT TRUE,
    Users_Type_account INT UNSIGNED NOT NULL,
    Users_created_at TIMESTAMP DEFAULT NOW()
);

-- table de liaison qui rassemble: user, exospine, équipement et nano-suits
CREATE TABLE Favorite (
    Favorite_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    Favorite_users_id INT UNSIGNED NOT NULL,
    Favorite_objet_id_fk INT UNSIGNED NOT NULL,

    CONSTRAINT fk_fav_user FOREIGN KEY (Favorite_users_id) REFERENCES Users(Users_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_fav_objet FOREIGN KEY (Favorite_objet_id_fk) REFERENCES Objet(Objet_id)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Locations (
    Locations_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    Locations_name_fr VARCHAR(30) NOT NULL,
    Locations_name_en VARCHAR(30) NOT NULL,
    Locations_country VARCHAR(20) NOT NULL,
    Locations_color VARCHAR(30) NOT NULL,
    Locations_icon_black VARCHAR(50) NOT NULL,
    Locations_icon_white VARCHAR(50) NOT NULL
);

CREATE TABLE StatsEVE (
    Stats_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    Stats_title_fr VARCHAR(255) NOT NULL,
    Stats_title_en VARCHAR(255) NOT NULL,
    Stats_bar BOOLEAN,
    Stats_value INT,
    Stats_value_max INT,
    Stats_decimal DECIMAL(6,1) CHECK (Stats_decimal BETWEEN -1000 AND 1000),
    Stats_icon VARCHAR(50) NOT NULL
);

CREATE TABLE Stores(
    Stores_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    Stores_title VARCHAR(50) NOT NULL,
    Stores_text VARCHAR(20) NOT NULL,
    Stores_text_2 VARCHAR(50) NOT NULL,
    Stores_picture VARCHAR(50) NOT NULL,
    Stores_picture_2 VARCHAR(50) NOT NULL,
    Store_link VARCHAR(60) NOT NULL
);

insert into Section (Section_id, Section_title, Section_icons_gray, Section_icons_black, Section_arrow)
values
    (1, "ARSENAL", "/icons/manufacturing_gray.svg", "/icons/manufacturing_black.svg", "/icons/mobile/arrow_down.svg"),
    (2, "MISSIONS", "/icons/rocket_launch_gray.svg", "/icons/rocket_launch_black.svg", "/icons/mobile/arrow_down.svg"),
    (3, "CARTES", "/icons/map_search_gray.svg", "/icons/map_search_black.svg", "/icons/mobile/arrow_down.svg"),
    (4, "COMPÉTENCES", "/icons/person_celebrate_gray.svg", "/icons/person_celebrate_black.svg", "/icons/mobile/arrow_down.svg"),
    (5, "BASE DE DONNÉES", "/icons/database_gray.svg", "/icons/database_black.svg", "/icons/mobile/arrow_down.svg");

insert into Arsenal (Arsenal_id, Arsenal_title, Arsenal_icons_gray, Arsenal_icons_black, Arsenal_link, Arsenal_section_id_fk)
values
    (1, "Exospine", "/icons/orthopedics_gray.svg", "/icons/orthopedics_black.svg", "exospine", 1),
    (2, "Équipement", "/icons/engineering_gray.svg", "/icons/engineering_black.svg", "gears", 1),
    (3, "Nano-combinaison", "/icons/apparel_gray.svg", "/icons/apparel_black.svg", "nano-suits", 1),
    (4, "Lunettes", "/icons/eyeglasses_gray.svg", "/icons/eyeglasses_black.svg", "glasses", 1),
    (5, "Boucles d'oreilles", "/icons/diamond_shine_gray.svg", "/icons/diamond_shine_black.svg", "earrings", 1),
    (6, "Coiffures", "/icons/self_care_gray.svg", "/icons/self_care_black.svg", "hair-styles", 1),
    (7, "Drones", "/icons/helicopter_gray.svg", "/icons/helicopter_black.svg", "drone", 1),
    (8, "Nano-combinaison - Lily", "/icons/apparel_gray.svg", "/icons/apparel_black.svg", "nano-suits-lily", 1),
    (9, "Nano-combinaison - Adam", "/icons/apparel_gray.svg", "/icons/apparel_black.svg", "nano-suits-adam", 1);

insert into TypeObjet (TypeObjet_id, TypeObjet_name)
values
    (1, "Exospine"),
    (2, "Gears"),
    (3, "Nano-suit"),
    (4, "Glasses"),
    (5, "Earrings"),
    (6, "Hairstyles"),
    (7, "Drone"),
    (8, "Nano-suit Lily"),
    (9, "Nano-suit Adam");

insert into Objet (Objet_id, Objet_arsenal_id_fk, Objet_type_id_fk)
values
    (1, 1, 1),
    (2, 1, 1),
    (3, 1, 1),
    (4, 1, 1),
    (5, 1, 1),
    (6, 1, 1),
    (7, 1, 1),
    (8, 1, 1),
    (9, 1, 1),
    (10, 1, 1),
    (11, 1, 1),
    (12, 1, 1),
    (13, 1, 1),
    (14, 1, 1),
    (15, 1, 1),
    (16, 1, 1),
    (17, 1, 1),
    (18, 1, 1),
    (19, 1, 1),
    (20, 1, 1),
    (21, 1, 1),
    (22, 1, 1),
    (23, 1, 1),
    (24, 1, 1),
    (25, 1, 2),
    (26, 1, 2)

   ;

insert into TraductionObjet (TraductionObjet_id, TraductionObjet_id_objet_fk, TraductionObjet_Langages, TraductionObjet_fields, TraductionObjet_value)
values
    (1, 1, "fr", "Titre", "Exospine de type camouflage"),
    (2, 1, "fr", "Skill_1", "Réduit le champ de vision des ennemis."),
    (3, 1, "fr", "Skill_2", "En cas d'exécution réussie, augmente de 17,5% la puissance des attaques au corps à corps pendant 10 secondes."),
    (4, 1, "fr", "Skill_3", "Restaure 15 % des PV maximum en cas d'exécution réussie."),
    (5, 1, "fr", "Text_1", "Exospine spécialisée dans la furtivité et l'exécution."),
    (6, 1, "fr", "Text_2", "Comme tous les modules d'équipement, chaque nouveau modèle d'exospine propose des fonctionnalités innovantes. Suite à sa refonte, cette exospine a été équipée d'une IA autonome."),
    (7, 2, "fr", "Titre", "Exospine Mk2 de type camouflage"),
    (8, 2, "fr", "Skill_1", "Réduit le champ de vision des ennemis."),
    (9, 2, "fr", "Skill_2", "En cas d'exécution réussie, augmente de 25% la puissance des attaques au corps à corps pendant 10 secondes."),
    (10, 2, "fr", "Skill_3", "Restaure 22.5 % des PV maximum en cas d'exécution réussie."),
    (11, 2, "fr", "Text_1", "Exospine Mk2 spécialisée dans la furtivité et l'exécution."),
    (12, 2, "fr", "Text_2", "Comme tous les modules d'équipement, chaque nouveau modèle d'exospine propose des fonctionnalités innovantes. Suite à sa refonte, cette exospine a été équipée d'une IA autonome."),
    (13, 3, "fr", "Titre", "Exospine de type enchaînement"),
    (14, 3, "fr", "Skill_1", "Augmente de 27 % la puissance des enchaînements de niveau 2 ou plus."),
    (15, 3, "fr", "Skill_2", "Augmente les dégâts critiques de 23 %."),
    (16, 3, "fr", "Skill_3", "Augmente de 30% le taux de coups critiques des enchaînements de niveau 4 ou plus."),
    (17, 3, "fr", "Text_1", "Exospine spécialisée dans l'amélioration des enchaînements."),
    (18, 3, "fr", "Text_2", "Les modules d'équipement offraient une expérience personnalisée réussie, mais leurs performances étaient limitées. Par conséquent, Eidos a collaboré avec Tetrastar pour produire des API de bas niveau et des modifications sophistiquées. La devise de cette évolution était « Changeons tout ce qui peut l'être »."),
    (19, 4, "fr", "Titre", "Exospine Mk2 de type enchaînement"),
    (20, 4, "fr", "Skill_1", "Augmente de 40 % la puissance des enchaînements de niveau 2 ou plus."),
    (21, 4, "fr", "Skill_2", "Augmente les dégâts critiques de 35 %."),
    (22, 4, "fr", "Skill_3", "Augmente de 45% le taux de coups critiques des enchaînements de niveau 4 ou plus."),
    (23, 4, "fr", "Text_1", "Exospine spécialisée dans l'amélioration des enchaînements."),
    (24, 4, "fr", "Text_2", "Les modules d'équipement offraient une expérience personnalisée réussie, mais leurs performances étaient limitées. Par conséquent, Eidos a collaboré avec Tetrastar pour produire des API de bas niveau et des modifications sophistiquées. La devise de cette évolution était « Changeons tout ce qui peut l'être »."),
    (25, 5, "fr", "Titre", "Exospine de type grenadier"),
    (26, 5, "fr", "Skill_1", "Augmente les dégâts et les effets des consommables de combat. Les Naytibas puissants ne sont pas affectés."),
    (27, 5, "fr", "Skill_2", "Augmente la zone d'effet des consommables de combat."),
    (28, 5, "fr", "Skill_3", "Augmente les dégâts et les effets des consommables de combat si l'ennemi est attaqué par-derrière."),
    (29, 5, "fr", "Text_1", "Exospine spécialisée dans l'amélioration des consommables de combat."),
    (30, 5, "fr", "Text_2", "Au cours de la bataille finale, le manque de ressources a contraint les ingénieurs à rassembler tout ce qu'ils trouvaient pour fabriquer modules et exospines. Si cela peut désormais sembler ridicule, ils n'avaient à ce moment-là aucune autre option. Ils ne pouvaient tout simplement pas attendre que la base orbitale leur envoie de l'équipement alors qu'ils affrontaient des hordes infinies de monstres."),
    (31, 6, "fr", "Titre", "Exospine Mk2 de type grenadier"),
    (32, 6, "fr", "Skill_1", "Augmente considérablement les dégâts et les effets des consommables de combat. Les Naytibas puissants ne sont pas affectés."),
    (33, 6, "fr", "Skill_2", "Augmente la zone d'effet des consommables de combat."),
    (34, 6, "fr", "Skill_3", "Augmente considérablement les dégâts et les effets des consommables de combat si l'ennemi est attaqué par-derrière."),
    (35, 6, "fr", "Text_1", "Exospine spécialisée dans l'amélioration des consommables de combat."),
    (36, 6, "fr", "Text_2", "Au cours de la bataille finale, le manque de ressources a contraint les ingénieurs à rassembler tout ce qu'ils trouvaient pour fabriquer modules et exospines. Si cela peut désormais sembler ridicule, ils n'avaient à ce moment-là aucune autre option. Ils ne pouvaient tout simplement pas attendre que la base orbitale leur envoie de l'équipement alors qu'ils affrontaient des hordes infinies de monstres."),
    (37, 7, "fr", "Titre", "Exospine de type impact"),
    (38, 7, "fr", "Skill_1", "Augmente de 9,5% le taux de coups critiques."),
    (39, 7, "fr", "Skill_2", "Lorsque les ennemis subissent un coup critique, cela libère une vague d'énergie instable qui inflige des dégâts en chaîne aux ennemis proches."),
    (40, 7, "fr", "Skill_3", "L'énergie instable inflige plus de dégâts en chaîne."),
    (41, 7, "fr", "Text_1", "Exospine spécialisée dans le combat contre plusieurs adversaires."),
    (42, 7, "fr", "Text_2", "Les nerfs quantiques intégrés à une exospine peuvent affecter le subconscient d'une IA. Il ne serait pas exagéré de dire qu'ils sont profondément enfouis dans le système neuronal. Plusieurs lanceurs d'alertes accusent les multinationales d'effectuer des écoutes illégales, d'implémenter des portes dérobées et de manipuler les IA, mais les médias ne semblent pas intéressés par le sujet."),
    (43, 8, "fr", "Titre", "Exospine Mk2 de type impact"),
    (44, 8, "fr", "Skill_1", "Augmente de 14 % le taux de coups critiques."),
    (45, 8, "fr", "Skill_2", "Lorsque les ennemis subissent un coup critique, cela libère une vague d'énergie instable qui inflige de puissants dégâts en chaîne aux ennemis proches."),
    (46, 8, "fr", "Skill_3", "L'énergie instable inflige plus de dégâts en chaîne."),
    (47, 8, "fr", "Text_1", "Exospine spécialisée dans le combat contre plusieurs adversaires."),
    (48, 8, "fr", "Text_2", "Les nerfs quantiques intégrés à une exospine peuvent affecter le subconscient d'une IA. Il ne serait pas exagéré de dire qu'ils sont profondément enfouis dans le système neuronal. Plusieurs lanceurs d'alertes accusent les multinationales d'effectuer des écoutes illégales, d'implémenter des portes dérobées et de manipuler les IA, mais les médias ne semblent pas intéressés par le sujet."),
    (49, 9, "fr", "Titre", "Exospine de type jugement"),
    (50, 9, "fr", "Skill_1", "Augmente de 15 % la recharge d'énergie tachyonique."),
    (51, 9, "fr", "Skill_2", "Réduit de 15% la consommation d'énergie tachyonique."),
    (52, 9, "fr", "Skill_3", "Interrompre volontairement le mode Tachy inflige des dégâts aux ennemis proches et les met à terre."),
    (53, 9, "fr", "Text_1", "Exospine spécialisée pour le mode Tachy."),
    (54, 9, "fr", "Text_2", "La guerre contre les Naytibas a impliqué de nombreux sacrifices, comme le prouvent ces modules d'équipement asymétriques utilisés pour les missions suicides. De nombreux légionnaires équipés de ces exospines sont certainement morts au combat en hurlant le nom de la Matri-Arche. Nul ne saura jamais s'ils la louaient ou s'ils la maudissaient."),
    (55, 10, "fr", "Titre", "Exospine Mk2 de type jugement"),
    (56, 10, "fr", "Skill_1", "Augmente de 22,5 % la recharge d'énergie tachyonique."),
    (57, 10, "fr", "Skill_2", "Réduit de 22,5 % la consommation d'énergie tachyonique."),
    (58, 10, "fr", "Skill_3", "Interrompre volontairement le mode Tachy inflige des dégâts considérables aux ennemis proches et les met à terre."),
    (59, 10, "fr", "Text_1", "Exospine spécialisée pour le mode Tachy."),
    (60, 10, "fr", "Text_2", "La guerre contre les Naytibas a impliqué de nombreux sacrifices, comme le prouvent ces modules d'équipement asymétriques utilisés pour les missions suicides. De nombreux légionnaires équipés de ces exospines sont certainement morts au combat en hurlant le nom de la Matri-Arche. Nul ne saura jamais s'ils la louaient ou s'ils la maudissaient."),
    (61, 11, "fr", "Titre", "Exospine de type œil de faucon"),
    (62, 11, "fr", "Skill_1", "Augmente la puissance des attaques à distance de 10%."),
    (63, 11, "fr", "Skill_2", "Augmente la capacité maximum de toutes les munitions."),
    (64, 11, "fr", "Skill_3", "Vous avez une chance de récupérer des munitions lorsque vous touchez le point faible d'un ennemi avec une attaque à distance."),
    (65, 11, "fr", "Text_1", "Exospine spécialisée dans l'amélioration des attaques à distance."),
    (66, 11, "fr", "Text_2", "Cette exospine est un module d'extension aussi innovant que puissant. Est-ce qu'elle semble hostile ? Elle est équipée de nano-nerfs quantiques développés par Tetrastar, le nec plus ultra en matière d'intelligence artificielle et d'extension des capacités."),
    (67, 12, "fr", "Titre", "Exospine Mk2 de type œil de faucon"),
    (68, 12, "fr", "Skill_1", "Augmente la puissance des attaques à distance de 15 %."),
    (69, 12, "fr", "Skill_2", "Augmente considérablement la capacité maximum de toutes les munitions."),
    (70, 12, "fr", "Skill_3", "Vous avez une forte chance de récupérer des munitions lorsque vous touchez le point faible d'un ennemi avec une attaque à distance."),
    (71, 12, "fr", "Text_1", "Exospine spécialisée dans l'amélioration des attaques à distance."),
    (72, 12, "fr", "Text_2", "Cette exospine est un module d'extension aussi innovant que puissant. Est-ce qu'elle semble hostile ? Elle est équipée de nano-nerfs quantiques développés par Tetrastar, le nec plus ultra en matière d'intelligence artificielle et d'extension des capacités."),
    (73, 13, "fr", "Titre", "Exospine de type protection"),
    (74, 13, "fr", "Skill_1", "Réduit de 10 % les dégâts infligés par les ennemis."),
    (75, 13, "fr", "Skill_2", "Le niveau de protection du bouclier augmente de un au maximum."),
    (76, 13, "fr", "Skill_3", "Si votre santé est de 20 % ou moins, vous avez une chance de récupérer des PV pendant 5 secondes lorsque vous bloquez ou parez une attaque."),
    (77, 13, "fr", "Text_1", "Exospine spécialisée dans la survie."),
    (78, 13, "fr", "Text_2", "À l'automne 2050, le PDG d'Eidos a présenté la toute dernière exospine de l'entreprise lors de sa conférence annuelle, « Nous avons commencé à créer nos propres précepteurs, lesquels donneront naissance à de meilleurs précepteurs, que nous pouvons ajuster et remplacer à notre guise. » La Matri-Arche ? Elle observait la scène en temps réel par le biais du RÉSEAU."),
    (79, 14, "fr", "Titre", "Exospine Mk2 de type protection"),
    (80, 14, "fr", "Skill_1", "Réduit de 15% les dégâts infligés par les ennemis."),
    (81, 14, "fr", "Skill_2", "Le niveau de protection du bouclier augmente de un au maximum. Le bouclier maximum augmente avec le niveau de protection."),
    (82, 14, "fr", "Skill_3", "Si votre santé est de 30 % ou moins, vous avez une chance de récupérer des PV pendant 5 secondes lorsque vous bloquez ou parez une attaque."),
    (83, 14, "fr", "Text_1", "Exospine spécialisée dans la survie."),
    (84, 14, "fr", "Text_2", "À l'automne 2050, le PDG d'Eidos a présenté la toute dernière exospine de l'entreprise lors de sa conférence annuelle, « Nous avons commencé à créer nos propres précepteurs, lesquels donneront naissance à de meilleurs précepteurs, que nous pouvons ajuster et remplacer à notre guise. » La Matri-Arche ? Elle observait la scène en temps réel par le biais du RÉSEAU."),
    (85, 15, "fr", "Titre", "Exospine de type récupération"),
    (86, 15, "fr", "Skill_1", "Augmente de 10% tous les effets de récupération."),
    (87, 15, "fr", "Skill_2", "Les dégâts subis sont réduits de 11,5 % pendant une durée fixe lorsque vous utilisez une potion."),
    (88, 15, "fr", "Skill_3", "Vous récupérez 100 points d'énergie Bêta lorsque vous utilisez une potion."),
    (89, 15, "fr", "Text_1", "Exospine spécialisée dans les capacités de récupération."),
    (90, 15, "fr", "Text_2", "Lorsque l'homme s'est donné pour mission de coloniser Mars, l'adaptation, la survie et la résistance aux conditions extrêmes sont entrées au centre des préoccupations. L'homéostasie renforcée et les capacités de rétablissement conférées par l'exospine étaient exceptionnelles, sans parler de son pouvoir analgésique. Les seuls effets secondaires connus sont des sensations étranges dans tout le corps, quelques erreurs de récupération et des soucis d'IA."),
    (91, 16, "fr", "Titre", "Exospine Mk2 de type récupération"),
    (92, 16, "fr", "Skill_1", "Augmente de 15 % tous les effets de récupération."),
    (93, 16, "fr", "Skill_2", "Les dégâts subis sont réduits de 17 % pendant une durée fixe lorsque vous utilisez une potion."),
    (94, 16, "fr", "Skill_3", "Vous récupérez 150 points d'énergie Bêta lorsque vous utilisez une potion."),
    (95, 16, "fr", "Text_1", "Exospine spécialisée dans les capacités de récupération."),
    (96, 16, "fr", "Text_2", "Lorsque l'homme s'est donné pour mission de coloniser Mars, l'adaptation, la survie et la résistance aux conditions extrêmes sont entrées au centre des préoccupations. L'homéostasie renforcée et les capacités de rétablissement conférées par l'exospine étaient exceptionnelles, sans parler de son pouvoir analgésique. Les seuls effets secondaires connus sont des sensations étranges dans tout le corps, quelques erreurs de récupération et des soucis d'IA."),
    (97, 17, "fr", "Titre", "Exospine de type réflexes"),
    (98, 17, "fr", "Skill_1", "Le bouclier se régénère plus vite lorsque vous êtes en garde."),
    (99, 17, "fr", "Skill_2", "Facilite l'exécution d'esquives parfaites."),
    (100, 17, "fr", "Skill_3", "Facilite l'exécution de parades parfaites."),
    (101, 17, "fr", "Text_1", "Exospine spécialisée dans la protection et l'esquive."),
    (102, 17, "fr", "Text_2", "La suprématie croissante des multinationales, centrée sur le monopole de la chaîne de valeurs, a conduit à un mouvement de résistance. Les citoyens étaient particulièrement critiques à l'égard de ces exospines, affirmant qu'elles contenaient des « véripuces ». Beaucoup pensaient que les sociétés telles qu'Eidos, Tetrastar et Orca Aerospace utilisaient secrètement les machines pour façonner la vie humaine à leur guise."),
    (103, 18, "fr", "Titre", "Exospine Mk2 de type réflexes"),
    (104, 18, "fr", "Skill_1", "Le bouclier se régénère plus vite lorsque vous êtes en garde. L'effet augmente lorsque vous utilisez de l'équipement Mk2."),
    (105, 18, "fr", "Skill_2", "Facilite l'exécution d'esquives parfaites. L'effet augmente lorsque vous utilisez de l'équipement Mk2."),
    (106, 18, "fr", "Skill_3", "Facilite l'exécution de parades parfaites. L'effet augmente lorsque vous utilisez de l'équipement Mk2."),
    (107, 18, "fr", "Text_1", "Exospine spécialisée dans la protection et l'esquive."),
    (108, 18, "fr", "Text_2", "La suprématie croissante des multinationales, centrée sur le monopole de la chaîne de valeurs, a conduit à un mouvement de résistance. Les citoyens étaient particulièrement critiques à l'égard de ces exospines, affirmant qu'elles contenaient des « véripuces ». Beaucoup pensaient que les sociétés telles qu'Eidos, Tetrastar et Orca Aerospace utilisaient secrètement les machines pour façonner la vie humaine à leur guise."),
    (109, 19, "fr", "Titre", "Exospine de type suppression"),
    (110, 19, "fr", "Skill_1", "Augmente de 18% la pénétration de bouclier."),
    (111, 19, "fr", "Skill_2", "Les ennemis restent à terre plus longtemps."),
    (112, 19, "fr", "Skill_3", "Augmente de 18 % les dégâts infligés aux ennemis à terre."),
    (113, 19, "fr", "Text_1", "Exospine spécialisée dans les capacités de mise à terre."),
    (114, 19, "fr", "Text_2", "Lorsque les plaintes portant sur les défaillances de la dernière exospine ont commencé à pleuvoir, le sujet a rapidement fait débat. Nombre d'utilisateurs affirmaient entendre la voix de la Matri-Arche. La voix d'une magnifique jeune fille gracile, qui murmurait des milliers de mots. Ce n'était bien évidemment qu'un bug qui a été rapidement corrigé grâce à une mise à jour. En tout cas, c'est la version officielle des faits."),
    (115, 20, "fr", "Titre", "Exospine Mk2 de type suppression"),
    (116, 20, "fr", "Skill_1", "Augmente de 24 % la pénétration de bouclier."),
    (117, 20, "fr", "Skill_2", "Les ennemis restent à terre beaucoup plus longtemps."),
    (118, 20, "fr", "Skill_3", "Augmente de 27% les dégâts infligés aux ennemis à terre."),
    (119, 20, "fr", "Text_1", "Exospine spécialisée dans les capacités de mise à terre."),
    (120, 20, "fr", "Text_2", "Lorsque les plaintes portant sur les défaillances de la dernière exospine ont commencé à pleuvoir, le sujet a rapidement fait débat. Nombre d'utilisateurs affirmaient entendre la voix de la Matri-Arche. La voix d'une magnifique jeune fille gracile, qui murmurait des milliers de mots. Ce n'était bien évidemment qu'un bug qui a été rapidement corrigé grâce à une mise à jour. En tout cas, c'est la version officielle des faits."),
    (121, 21, "fr", "Titre", "Exospine de type transe Bêta"),
    (122, 21, "fr", "Skill_1", "Augmente l'énergie Bêta récupérée de 12 %."),
    (123, 21, "fr", "Skill_2", "Augmente de 12 % la puissance de toutes les compétences Bêta."),
    (124, 21, "fr", "Skill_3", "Si une compétence Bêta touche un ennemi, elle a une chance de vous plonger en transe. Les compétences Bêta ne consomment pas d'énergie Bêta tant que vous êtes en transe."),
    (125, 21, "fr", "Text_1", "Exospine spécialisée dans l'amélioration des compétences Bêta."),
    (126, 21, "fr", "Text_2", "Hélas, le rendement des semi-conducteurs quantiques Tetrastar était très faible, Les exospines étant des modules particulièrement onéreux, les quantités étaient limitées. Toutefois, en les présentant comme des objets de luxe, Tetrastar est parvenue à leur façonner une image très éloignée des modules d'équipement ordinaires"),
    (127, 22, "fr", "Titre", "Exospine Mk2 de type transe Bêta"),
    (128, 22, "fr", "Skill_1", "Augmente l'énergie Bêta récupérée de 15 %."),
    (129, 22, "fr", "Skill_2", "Augmente de 15 % la puissance de toutes les compétences Bêta."),
    (130, 22, "fr", "Skill_3", "Si une compétence Bêta touche un ennemi, elle a une chance de vous plonger en transe. Les compétences Bêta ne consomment pas d'énergie Bêta tant que vous êtes en transe."),
    (131, 22, "fr", "Text_1", "Exospine spécialisée dans l'amélioration des compétences Bêta."),
    (132, 22, "fr", "Text_2", "Hélas, le rendement des semi-conducteurs quantiques Tetrastar était très faible, Les exospines étant des modules particulièrement onéreux, les quantités étaient limitées. Toutefois, en les présentant comme des objets de luxe, Tetrastar est parvenue à leur façonner une image très éloignée des modules d'équipement ordinaires"),
    (133, 23, "fr", "Titre", "Exospine de type transe spontanée"),
    (134, 23, "fr", "Skill_1", "Augmente la jauge maximum d'énergie spontanée de 600 points."),
    (135, 23, "fr", "Skill_2", "Augmente la puissance des compétences spontanées de 30 %."),
    (136, 23, "fr", "Skill_3", "Vous récupérez 50 points d'énergie spontanée lorsque vous effectuez un enchaînement de niveau 4 ou plus."),
    (137, 23, "fr", "Text_1", "Exospine spécialisée dans l'amélioration des compétences spontanées."),
    (138, 23, "fr", "Text_2", "Lorsque la Dernière Guerre s'est transformée en conflit total tout droit issu de nos pires cauchemars, la Matri-Arche a réquisitionné toutes les infrastructures de « l'humanité », La majorité des modules d'équipement atypiques planifiés ou produits à cette époque ont totalement disparu lorsque nous avons dû nous retrancher en orbite. C'est notamment le cas des exospines exclusivement conçues pour le combat."),
    (139, 24, "fr", "Titre", "Exospine Mk2 de type transe spontanée"),
    (140, 24, "fr", "Skill_1", "Augmente la jauge maximum d'énergie spontanée de 800 points."),
    (141, 24, "fr", "Skill_2", "Augmente la puissance des compétences spontanées de 45 %."),
    (142, 24, "fr", "Skill_3", "Vous récupérez 75 points d'énergie spontanée lorsque vous effectuez un enchaînement de niveau 4 ou plus."),
    (143, 24, "fr", "Text_1", "Exospine spécialisée dans l'amélioration des compétences spontanées."),
    (144, 24, "fr", "Text_2", "Lorsque la Dernière Guerre s'est transformée en conflit total tout droit issu de nos pires cauchemars, la Matri-Arche a réquisitionné toutes les infrastructures de « l'humanité », La majorité des modules d'équipement atypiques planifiés ou produits à cette époque ont totalement disparu lorsque nous avons dû nous retrancher en orbite. C'est notamment le cas des exospines exclusivement conçues pour le combat."),
    (145, 25, "fr", "Titre", "Équipement à double tranchant"),
    (146, 25, "fr", "Skill_1", "Puissance"),
    (147, 25, "fr", "Skill_2", "Dégâts subis"),
    (148, 25, "fr", "Text_1", "Augmente considérablement votre puissance, mais vous subissez plus de dégâts."),
    (149, 25, "fr", "Text_2", "La doctrine de l'Épée à double tranchant est largement adoptée par les Sentinelles de Xion. Dans l'état actuel des choses, la cité ne peut pas se permettre de petites escarmouches et doit donc éliminer les Naytibas au plus vite. Par conséquent, bon nombre de Sentinelles optent pour cette configuration de modules plutôt extrême."),
    (150, 26, "en", "Titre", "Double Edged Gear"),
    (151, 26, "en", "Skill_1", "Attack Power"),
    (152, 26, "en", "Skill_2", "Damage Taken"),
    (153, 26, "en", "Text_1", "Greatly increases Attack Power, but you'll take more Damage."),
    (154, 26, "en", "Text_2", "The Double Edged Sword is a major doctrine of Xion's sentry. Xion cannot afford to fight small battles at this time, so the Naytibas must be defeated quickly. As such, the Sentinels have their gear modules set up in very extreme configurations.")
    ;

insert into AttributObjet (AttributObjet, AttributObjet_id_objet_fk, AttributObjet_name, AttributObjet_value)
values
    (1, 1, "Exospine_bar_1", "true"),
    (2, 1, "Exospine_bar_2", "true"),
    (3, 1, "Exospine_bar_3", "true"),
    (4, 1, "Exospine_stat_2", "17.5"),
    (5, 1, "Exospine_stat_3", "15"),
    (6, 1, "Exospine_bar", "Exospine_bar"),
    (7, 1, "Exospine_icon", "/icons/network_intelligence_white.svg"),
    (8, 1, "Exospine_icon_colored", "/icons/network_intelligence_orange.svg"),
    (9, 2, "Exospine_bar_1", "true"),
    (10, 2, "Exospine_bar_2", "true"),
    (11, 2, "Exospine_bar_3", "true"),
    (12, 2, "Exospine_stat_2", "25"),
    (13, 2, "Exospine_stat_3", "22.5"),
    (14, 2, "Exospine_bar", "Exospine_bar"),
    (15, 2, "Exospine_icon_Mk2", "/icons/network_intelligence_update_white.svg"),
    (16, 2, "Exospine_icon_colored_Mk2", "/icons/network_intelligence_update_orange.svg"),
    (17, 3, "Exospine_bar_1", "true"),
    (18, 3, "Exospine_bar_2", "true"),
    (19, 3, "Exospine_bar_3", "true"),
    (20, 3, "Exospine_stat_1", "27"),
    (21, 3, "Exospine_stat_2", "23"),
    (22, 3, "Exospine_stat_3", "30"),
    (23, 3, "Exospine_bar", "Exospine_bar"),
    (24, 3, "Exospine_icon", "/icons/network_intelligence_white.svg"),
    (25, 3, "Exospine_icon_colored", "/icons/network_intelligence_orange.svg"),
    (26, 4, "Exospine_bar_1", "true"),
    (27, 4, "Exospine_bar_2", "true"),
    (28, 4, "Exospine_bar_3", "true"),
    (29, 4, "Exospine_stat_1", "40"),
    (30, 4, "Exospine_stat_2", "35"),
    (31, 4, "Exospine_stat_3", "45"),
    (32, 4, "Exospine_bar", "Exospine_bar"),
    (33, 4, "Exospine_icon_Mk2", "/icons/network_intelligence_update_white.svg"),
    (34, 4, "Exospine_icon_colored_Mk2", "/icons/network_intelligence_update_orange.svg"),
    (35, 5, "Exospine_bar_1", "true"),
    (36, 5, "Exospine_bar_2", "true"),
    (37, 5, "Exospine_bar_3", "true"),
    (38, 5, "Exospine_bar", "Exospine_bar"),
    (39, 5, "Exospine_icon", "/icons/network_intelligence_white.svg"),
    (40, 5, "Exospine_icon_colored", "/icons/network_intelligence_orange.svg"),
    (41, 6, "Exospine_bar_1", "true"),
    (42, 6, "Exospine_bar_2", "true"),
    (43, 6, "Exospine_bar_3", "true"),
    (44, 6, "Exospine_bar", "Exospine_bar"),
    (45, 6, "Exospine_icon_Mk2", "/icons/network_intelligence_update_white.svg"),
    (46, 6, "Exospine_icon_colored_Mk2", "/icons/network_intelligence_update_orange.svg"),
    (47, 7, "Exospine_bar_1", "true"),
    (48, 7, "Exospine_bar_2", "true"),
    (49, 7, "Exospine_bar_3", "true"),
    (50, 7, "Exospine_stat_1", "9.5"),
    (51, 7, "Exospine_bar", "Exospine_bar"),
    (52, 7, "Exospine_icon", "/icons/network_intelligence_white.svg"),
    (53, 7, "Exospine_icon_colored", "/icons/network_intelligence_orange.svg"),
    (54, 8, "Exospine_bar_1", "true"),
    (55, 8, "Exospine_bar_2", "true"),
    (56, 8, "Exospine_bar_3", "true"),
    (57, 8, "Exospine_stat_1", "14"),
    (58, 8, "Exospine_bar", "Exospine_bar"),
    (59, 8, "Exospine_icon_Mk2", "/icons/network_intelligence_update_white.svg"),
    (60, 8, "Exospine_icon_colored_Mk2", "/icons/network_intelligence_update_orange.svg"),
    (61, 9, "Exospine_bar_1", "true"),
    (62, 9, "Exospine_bar_2", "true"),
    (63, 9, "Exospine_bar_3", "true"),
    (64, 9, "Exospine_stat_1", "15"),
    (65, 9, "Exospine_stat_2", "15"),
    (66, 9, "Exospine_bar", "Exospine_bar"),
    (67, 9, "Exospine_icon", "/icons/network_intelligence_white.svg"),
    (68, 9, "Exospine_icon_colored", "/icons/network_intelligence_orange.svg"),
    (69, 10, "Exospine_bar_1", "true"),
    (70, 10, "Exospine_bar_2", "true"),
    (71, 10, "Exospine_bar_3", "true"),
    (72, 10, "Exospine_stat_1", "22.5"),
    (73, 10, "Exospine_stat_2", "22.5"),
    (74, 10, "Exospine_bar", "Exospine_bar"),
    (75, 10, "Exospine_icon_Mk2", "/icons/network_intelligence_update_white.svg"),
    (76, 10, "Exospine_icon_colored_Mk2", "/icons/network_intelligence_update_orange.svg"),
    (77, 11, "Exospine_bar_1", "true"),
    (78, 11, "Exospine_bar_2", "true"),
    (79, 11, "Exospine_bar_3", "true"),
    (80, 11, "Exospine_stat_1", "10"),
    (81, 11, "Exospine_bar", "Exospine_bar"),
    (82, 11, "Exospine_icon", "/icons/network_intelligence_white.svg"),
    (83, 11, "Exospine_icon_colored", "/icons/network_intelligence_orange.svg"),
    (84, 12, "Exospine_bar_1", "true"),
    (85, 12, "Exospine_bar_2", "true"),
    (86, 12, "Exospine_bar_3", "true"),
    (87, 12, "Exospine_stat_1", "15"),
    (88, 12, "Exospine_bar", "Exospine_bar"),
    (89, 12, "Exospine_icon_Mk2", "/icons/network_intelligence_update_white.svg"),
    (90, 12, "Exospine_icon_colored_Mk2", "/icons/network_intelligence_update_orange.svg"),
    (91, 13, "Exospine_bar_1", "true"),
    (92, 13, "Exospine_bar_2", "true"),
    (93, 13, "Exospine_bar_3", "true"),
    (94, 13, "Exospine_stat_1", "10"),
    (95, 13, "Exospine_stat_3", "20"),
    (96, 13, "Exospine_bar", "Exospine_bar"),
    (97, 13, "Exospine_icon", "/icons/network_intelligence_white.svg"),
    (98, 13, "Exospine_icon_colored", "/icons/network_intelligence_orange.svg"),
    (99, 14, "Exospine_bar_1", "true"),
    (100, 14, "Exospine_bar_2", "true"),
    (101, 14, "Exospine_bar_3", "true"),
    (102, 14, "Exospine_stat_1", "15"),
    (103, 14, "Exospine_stat_3", "30"),
    (104, 14, "Exospine_bar", "Exospine_bar"),
    (105, 14, "Exospine_icon_Mk2", "/icons/network_intelligence_update_white.svg"),
    (106, 14, "Exospine_icon_colored_Mk2", "/icons/network_intelligence_update_orange.svg"),
    (107, 15, "Exospine_bar_1", "true"),
    (108, 15, "Exospine_bar_2", "true"),
    (109, 15, "Exospine_bar_3", "true"),
    (110, 15, "Exospine_stat_1", "10"),
    (111, 15, "Exospine_stat_2", "11.5"),
    (112, 15, "Exospine_stat_1_eng_beta", "100"),
    (113, 15, "Exospine_bar", "Exospine_bar"),
    (114, 15, "Exospine_icon", "/icons/network_intelligence_white.svg"),
    (115, 15, "Exospine_icon_colored", "/icons/network_intelligence_orange.svg"),
    (116, 16, "Exospine_bar_1", "true"),
    (117, 16, "Exospine_bar_2", "true"),
    (118, 16, "Exospine_bar_3", "true"),
    (119, 16, "Exospine_stat_1", "15"),
    (120, 16, "Exospine_stat_2", "17"),
    (121, 16, "Exospine_stat_1_eng_beta", "150"),
    (122, 16, "Exospine_bar", "Exospine_bar"),
    (123, 16, "Exospine_icon_Mk2", "/icons/network_intelligence_update_white.svg"),
    (124, 16, "Exospine_icon_colored_Mk2", "/icons/network_intelligence_update_orange.svg"),
    (125, 17, "Exospine_bar_1", "true"),
    (126, 17, "Exospine_bar_2", "true"),
    (127, 17, "Exospine_bar_3", "true"),
    (128, 17, "Exospine_bar", "Exospine_bar"),
    (129, 17, "Exospine_icon", "/icons/network_intelligence_white.svg"),
    (130, 17, "Exospine_icon_colored", "/icons/network_intelligence_orange.svg"),
    (131, 18, "Exospine_bar_1", "true"),
    (132, 18, "Exospine_bar_2", "true"),
    (133, 18, "Exospine_bar_3", "true"),
    (134, 18, "Exospine_bar", "Exospine_bar"),
    (135, 18, "Exospine_icon_Mk2", "/icons/network_intelligence_update_white.svg"),
    (136, 18, "Exospine_icon_colored_Mk2", "/icons/network_intelligence_update_orange.svg"),
    (137, 19, "Exospine_bar_1", "true"),
    (138, 19, "Exospine_bar_2", "true"),
    (139, 19, "Exospine_bar_3", "true"),
    (140, 19, "Exospine_stat_1", "18"),
    (141, 19, "Exospine_stat_3", "18"),
    (142, 19, "Exospine_bar", "Exospine_bar"),
    (143, 19, "Exospine_icon", "/icons/network_intelligence_white.svg"),
    (144, 19, "Exospine_icon_colored", "/icons/network_intelligence_orange.svg"),
    (145, 20, "Exospine_bar_1", "true"),
    (146, 20, "Exospine_bar_2", "true"),
    (147, 20, "Exospine_bar_3", "true"),
    (148, 20, "Exospine_stat_1", "24"),
    (149, 20, "Exospine_stat_3", "27"),
    (150, 20, "Exospine_bar", "Exospine_bar"),
    (151, 20, "Exospine_icon_Mk2", "/icons/network_intelligence_update_white.svg"),
    (152, 20, "Exospine_icon_colored_Mk2", "/icons/network_intelligence_update_orange.svg"),
    (153, 21, "Exospine_bar_1", "true"),
    (154, 21, "Exospine_bar_2", "true"),
    (155, 21, "Exospine_bar_3", "true"),
    (156, 21, "Exospine_stat_1", "12"),
    (157, 21, "Exospine_stat_2", "12"),
    (158, 21, "Exospine_bar", "Exospine_bar"),
    (159, 21, "Exospine_icon", "/icons/network_intelligence_white.svg"),
    (160, 21, "Exospine_icon_colored", "/icons/network_intelligence_orange.svg"),
    (161, 22, "Exospine_bar_1", "true"),
    (162, 22, "Exospine_bar_2", "true"),
    (163, 22, "Exospine_bar_3", "true"),
    (164, 22, "Exospine_stat_1", "15"),
    (165, 22, "Exospine_stat_2", "15"),
    (166, 22, "Exospine_bar", "Exospine_bar"),
    (167, 22, "Exospine_icon_Mk2", "/icons/network_intelligence_update_white.svg"),
    (168, 22, "Exospine_icon_colored_Mk2", "/icons/network_intelligence_update_orange.svg"),
    (169, 23, "Exospine_bar_1", "true"),
    (170, 23, "Exospine_bar_2", "true"),
    (171, 23, "Exospine_bar_3", "true"),
    (172, 23, "Exospine_stat_1_eng_brust", "600"),
    (173, 23, "Exospine_stat_2", "30"),
    (174, 23, "Exospine_stat_1_eng_brust", "50"),
    (175, 23, "Exospine_bar", "Exospine_bar"),
    (176, 23, "Exospine_icon", "/icons/network_intelligence_white.svg"),
    (177, 23, "Exospine_icon_colored", "/icons/network_intelligence_orange.svg"),
    (178, 24, "Exospine_bar_1", "true"),
    (179, 24, "Exospine_bar_2", "true"),
    (180, 24, "Exospine_bar_3", "true"),
    (181, 24, "Exospine_stat_1_eng_brust", "800"),
    (182, 24, "Exospine_stat_2", "45"),
    (183, 24, "Exospine_stat_1_eng_brust", "75"),
    (184, 24, "Exospine_bar", "Exospine_bar"),
    (185, 24, "Exospine_icon_Mk2", "/icons/network_intelligence_update_white.svg"),
    (186, 24, "Exospine_icon_colored_Mk2", "/icons/network_intelligence_update_orange.svg"),
    (187, 25, "Gears_star_1", "true"),
    (188, 25, "Gears_star_2", "false"),
    (189, 25, "Gears_star_3", "false"),
    (190, 25, "Gears_stat_1", "15"),
    (191, 25, "Gears_stat_2", "23"),
    (192, 25, "Gears_star", "/icons/star_gray.svg"),
    (193, 25, "Gears_star_colored", "/icons/star_fill_orange.webp"),
    (194, 25, "Gears_icon", "/icons/network_intelligence_white.svg"),
    (195, 25, "Gears_icon_colored", "/icons/network_intelligence_orange.svg"),
    (196, 26, "Gears_star_1", "true"),
    (197, 26, "Gears_star_2", "false"),
    (198, 26, "Gears_star_3", "false"),
    (199, 26, "Gears_stat_1", "15"),
    (200, 26, "Gears_stat_2", "23"),
    (201, 26, "Gears_star", "/icons/star_gray.svg"),
    (202, 26, "Gears_star_colored", "/icons/star_fill_orange.webp"),
    (203, 26, "Gears_icon", "/icons/network_intelligence_white.svg"),
    (204, 26, "Gears_icon_colored", "/icons/network_intelligence_orange.svg")
    ;


insert into Locations(Locations_id, Locations_name_fr, Locations_name_en, Locations_country, Locations_color, Locations_icon_black, Locations_icon_white)
values
(1, "Xion", "Xion", "USA", "--linear-xion", "/icons/locations/xion_black.svg", "/icons/locations/xion_white.svg"),
(2, "Eidos 7", "Eidos 7", "Ukraine", "--linear-eidos7", "/icons/locations/eidos_7_black.svg", "/icons/locations/eidos_7_white.svg"),
(3, "Eidos 9", "Eidos 9", "Ukraine", "--linear-eidos9", "/icons/locations/eidos_9_black.svg", "/icons/locations/eidos_9_white.svg"),
(4, "Les terres désolées", "The wastelands", "USA", "--linear-thewastelands", "/icons/locations/the_wastelands_black.svg", "/icons/locations/the_wastelands_white.svg"),
(5, "Plateau levoir", "Altess levoir", "USA", "--linear-altesslevoire", "/icons/locations/altess_levoire_black.svg", "/icons/locations/altess_levoire_white.svg"),
(6, "Le grand désert", "The great desert", "France", "--linear-thegreatdesert", "/icons/locations/the_great_desert_black.svg", "/icons/locations/the_great_desert_white.svg"),
(7, "Fosse levoir", "Abyss levoir", "USA", "--linear-abysslevoire", "/icons/locations/abyss_levoire_black.svg", "/icons/locations/abyss_levoire_white.svg"),
(8, "Matrix 11", "Matrix 11", "France", "--linear-matrix11", "/icons/locations/matrix_11_black.svg", "/icons/locations/matrix_11_white.svg"),
(9, "Obélisque 4", "Spire 4", "New-Caledonia", "--linear-spire4", "/icons/locations/spire_4_black.svg", "/icons/locations/spire_4_white.svg")
;

insert into StatsEVE (Stats_id, Stats_title_fr ,Stats_title_en, Stats_bar, Stats_value, Stats_value_max, Stats_decimal, Stats_icon)
values
    (1, "PV max", "Max HP", TRUE, 2500, 6500, NULL, "/icons/stats_eve/stats_eve_black.svg"),
    (2, "Bouclier max", "Max Shield", TRUE, 500, 2000, NULL, "/icons/stats_eve/stats_eve_black.svg"),
    (3, "Énergie Bêta max", "Max Beta Energy", TRUE, 300, 2800, NULL, "/icons/stats_eve/stats_eve_black.svg"),
    (4, "Énergie Somptanée max", "Max Somptanée Energy", TRUE, 1600, 3000, NULL, "/icons/stats_eve/stats_eve_black.svg"),
    (5, "Puissance", "Attack Power", TRUE, 530, 1300, NULL, "/icons/stats_eve/stats_eve_black.svg"),
    (6, "Dégâts sur boucliers", "Damage to shields", TRUE, 100, 250, NULL, "/icons/stats_eve/stats_eve_black.svg"),
    (7, "Taux de coups critiques", "Critical Rate", TRUE, NULL, NULL, 5, "/icons/stats_eve/stats_eve_black.svg"),
    (8, "Dégâts critiques", "Critical Damage", TRUE,  NULL, NULL, 150, "/icons/stats_eve/stats_eve_black.svg"),
    (9, "Bonus de puissance des compétences Bêta", "Beta Skill Power Bonus", FALSE, NULL, NULL, 15, "/icons/stats_eve/stats_eve_black.svg"),
    (10, "Vitesse d'attaque", "Attack Speed", FALSE, NULL, NULL, 118, "/icons/stats_eve/stats_eve_black.svg"),
    (11, "Réduction des dégâts au corps à corps", "Melee Damage Reduction", FALSE, NULL, NULL, 118, "/icons/stats_eve/stats_eve_black.svg"),
    (12, "Réduction des dégâts à distance", "Ranged Damage Reduction", FALSE, NULL, NULL, -38, "/icons/stats_eve/stats_eve_black.svg"),
    (13, "Bonus de recharge d’énergie Bêta", "Beta Energy Recharge Bonus", FALSE, NULL, NULL, 15, "/icons/stats_eve/stats_eve_black.svg"),
    (14, "Dépense d’énergie tachyonique réduite", "Tachyon Energy Cost Reduction", FALSE, NULL, NULL, 20, "/icons/stats_eve/stats_eve_black.svg")
    ;


insert into Stores (Stores_id, Stores_title, Stores_text, Stores_text_2, Stores_picture, Stores_picture_2, Store_link)
values
    (1, "Playstation Store", "BUY", "The game", "/icons/playstation_store_bag_white.svg", "/icons/playstation_store_bag_blue.svg", "https://store.playstation.com/fr-fr/concept/10006891"),
    (2, "Steam", "BUY", "The game", "/icons/steam_play-here_white.svg", "/icons/steam_play-here_white.svg", "https://store.steampowered.com/app/3489700/Stellar_Blade/");

insert into Users (Users_id, Users_pseudo, Users_email, Users_hashed_password, Users_is_accept_cgu, Users_Type_account, Users_created_at)
values
    (1, "NicolasG38", "NG38@outlook.fr", "$argon2id$v=19$m=65536,t=3,p=1$GaGOi91/X2k8zxNHuA0Wqg$3VpTSJSKdSYlotcIzWZMST9FC0+2OZW+gw3YMmyJ6K0", TRUE, "9", "2025-07-01 00:00:00" );