import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "../../context/AuthContext";
import { MenuMobileProvider } from "../../context/MenuMobileContext";
import { LanguageProvider } from "../../context/LangContext";
import NavMobile from "../../components/0_Home/NavMobile";
import SubSection from "../../components/0_Home/SubSection";

export const metadata: Metadata = {
	title: "Blood-Edge.com",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<AuthProvider>
					<MenuMobileProvider>
						<LanguageProvider>
							<NavMobile>
								<SubSection key={1} />
							</NavMobile>
							{children}
						</LanguageProvider>
					</MenuMobileProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
